module com.crschnick.pdxu.app {
    uses com.crschnick.pdxu.app.core.EditorProvider;
    requires com.realityinteractive.imageio.tga;
    requires org.apache.commons.lang;
    requires org.apache.commons.io;
    requires com.fasterxml.jackson.core;
    requires com.fasterxml.jackson.databind;
    requires net.nikr.dds;
    requires javafx.base;
    requires javafx.graphics;
    requires javafx.controls;
    requires javafx.media;
    requires org.jnativehook;
    requires jdk.localedata;
    requires org.kordamp.iconli.core;
    requires org.kordamp.ikonli.javafx;
    requires com.jfoenix;
    requires com.google.gson;
    requires org.slf4j;
    requires org.slf4j.simple;
    requires io.sentry;
    requires java.logging;
    requires org.apache.commons.collections4;
    requires java.desktop;
    requires java.net.http;
    requires com.crschnick.pdxu.model;
    requires com.crschnick.pdxu.io;
    requires jdk.httpserver;

    exports com.crschnick.pdxu.app;
    exports com.crschnick.pdxu.app.installation;
    exports com.crschnick.pdxu.app.util;
    exports com.crschnick.pdxu.app.core;
    exports com.crschnick.pdxu.app.util.integration;
    exports com.crschnick.pdxu.app.gui;
    exports com.crschnick.pdxu.app.gui.game;
    exports com.crschnick.pdxu.app.savegame;
    exports com.crschnick.pdxu.app.lang;
    exports com.crschnick.pdxu.app.core.settings;
    exports com.crschnick.pdxu.app.gui.dialog;
    exports com.crschnick.pdxu.app.installation.dist;
    exports com.crschnick.pdxu.app.info;

    opens com.crschnick.pdxu.app to com.fasterxml.jackson.databind;
    opens com.crschnick.pdxu.app.info to com.fasterxml.jackson.databind;
    opens com.crschnick.pdxu.app.info.eu4 to com.fasterxml.jackson.databind;
    opens com.crschnick.pdxu.app.info.ck3 to com.fasterxml.jackson.databind;
    opens com.crschnick.pdxu.app.info.hoi4 to com.fasterxml.jackson.databind;
    opens com.crschnick.pdxu.app.info.stellaris to com.fasterxml.jackson.databind;
    opens com.crschnick.pdxu.app.info.ck2 to com.fasterxml.jackson.databind;
    opens com.crschnick.pdxu.app.info.vic2 to com.fasterxml.jackson.databind;
}